version: '3.5'

services:
  web:
    image: totakoko/totakoko.com:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.totakoko.rule=Host(`totakoko.com`)"
      - "traefik.http.services.totakoko.loadbalancer.server.port=80"

networks:
  web:
    external: true
