version: '3'
services:
  netdata:
    image: netdata/netdata:v1.31.0
    restart: unless-stopped
    hostname: totakoko.com
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - RESCRAMBLE=true
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`netdata.totakoko.com`)"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      - "traefik.http.routers.netdata.middlewares=netdata"
      - "traefik.http.middlewares.netdata.basicauth.users=${BASIC_AUTH}"

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  web:
    external: true
