version: '3.5'

services:
  ui:
    image: registry.totakoko.com/home/spotiblind:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotiblind.rule=Host(`spotiblind.totakoko.com`)"
      - "traefik.http.services.spotiblind.loadbalancer.server.port=5000"

networks:
  web:
    external: true
